// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {environment} from '../models';

export function GetFlights():Promise<environment.Flight>;

export function Greet(arg1:string):Promise<string>;
